% case 1: z = 0, m = 0 (correct measurement)
% case 2: z = 1, m = 0 (wrong measurement)
% case 3: z = 0, m = 1 (wrong measurement)
% case 4: z = 1, m = 1 (correct measurement)

calcPMeasurement = @(Z, M, pTrueDetection, pFalseDetection) ...
    Z .* M .* pTrueDetection + ...
    Z .* (~M) .* pFalseDetection + ...
    (~Z) .* M .* pFalseDetection + ...
    (~Z) .* (~M) .* pTrueDetection;